name: 'Build & Test'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['lts/*']

    steps:
    - uses: actions/checkout@v2
    - name: Testing against Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm lint --if-present
    - run: npm run build --if-present
    - run: npm test --if-present
      env:
        CI: true
